name: tests
on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            generator: msvc
            arch: x64
            config: RelWithDebInfo
          - os: windows-latest
            generator: msvc
            arch: win32
            config: [1, 2]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} / ${{ matrix.generator }} / ${{ matrix.arch }}
    steps:
      - run: echo Run ${{ matrix.os }} / ${{ matrix.generator }} / ${{ matrix.arch }} / ${{ matrix.config }}
