name: tests
on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        variant:
          - {os: windows-latest, generator: msvc, arch: x64, config: Release} 
          - {os: ubuntu-latest, generator: clang, arch: x64, config: Release} 
          - {os: macos-latest, generator: clang, arch: x64, config: Release} 

    runs-on: ${{ matrix.variant.os }}
    name: ${{ matrix.variant.os }} / ${{ matrix.variant.generator }} / ${{ matrix.variant.arch }} / ${{ matrix.python-version }}
    steps:
      - name: A
        if: matrix.variant.os == 'windows-latest'
        run: |
          C:\msys64\usr\bin\pacman.exe --confirm -Syuu
          C:\msys64\usr\bin\pacman.exe --confirm -Ss gdb
          